### ISSUE TITLE
Bug: cannot convert float NaN to integer 

### ISSUE THREAD

**Issue by webgisdeveloper** [Global-Flood-Assessment/ModelOfModels#14]
ValueError: cannot convert float NaN to integer

rawdata/gfms/Flood_byStor_2021061721.csv=====================] 100.0% ...aqid
Traceback (most recent call last):
  File "datatool.py", line 646, in <module>
    main()
  File "datatool.py", line 639, in main
    run_cron_fix(args.fixdate)
  File "datatool.py", line 590, in run_cron_fix
    fix_duration(fix_list,folder=gfmsdata,fixfolder=gfmsdata_fix)
  File "/home/geogateway/ModelofModels/data/GFMS_duration_fix.py", line 40, in fix_duration
    df['GFMS_Duration'] = df.apply(lambda row: 3 + int(row.GFMS_Duration0) if (row.GFMS_TotalArea_km > 100.0) else '0', axis = 1)
  File "/home/geogateway/miniconda3/lib/python3.8/site-packages/pandas/core/frame.py", line 7765, in apply
    return op.get_result()
  File "/home/geogateway/miniconda3/lib/python3.8/site-packages/pandas/core/apply.py", line 185, in get_result
    return self.apply_standard()
  File "/home/geogateway/miniconda3/lib/python3.8/site-packages/pandas/core/apply.py", line 276, in apply_standard
    results, res_index = self.apply_series_generator()
  File "/home/geogateway/miniconda3/lib/python3.8/site-packages/pandas/core/apply.py", line 290, in apply_series_generator
    results[i] = self.f(v)
  File "/home/geogateway/ModelofModels/data/GFMS_duration_fix.py", line 40, in <lambda>
    df['GFMS_Duration'] = df.apply(lambda row: 3 + int(row.GFMS_Duration0) if (row.GFMS_TotalArea_km > 100.0) else '0', axis = 1)
ValueError: cannot convert float NaN to integer

**Comment by webgisdeveloper** [comment]
Flood_byStor_2021061621.csv is generated correctly, (file size is not right)
