### ISSUE TITLE
GFMS data issue

### ISSUE THREAD

**Issue by webgisdeveloper** [Global-Flood-Assessment/ModelOfModels#8]
```
cron_data/gfms/Flood_byStor_2020122812.csv
Traceback (most recent call last):
  File "datatool.py", line 632, in <module>
    main()
  File "datatool.py", line 627, in main
    run_cron_fix(args.fixdate)
  File "datatool.py", line 574, in run_cron_fix
    fix_duration(fix_list,folder=gfmsdata,fixfolder=gfmsdata_fix)
  File "/home/geogateway/ModelofModels/data/GFMS_duration_fix.py", line 40, in fix_duration
    df['GFMS_Duration'] = df.apply(lambda row: 3 + int(row.GFMS_Duration0) if (row.GFMS_TotalArea_km > 100.0) else '0', axis = 1)
  File "/home/geogateway/miniconda3/lib/python3.7/site-packages/pandas/core/frame.py", line 6878, in apply
    return op.get_result()
  File "/home/geogateway/miniconda3/lib/python3.7/site-packages/pandas/core/apply.py", line 186, in get_result
    return self.apply_standard()
  File "/home/geogateway/miniconda3/lib/python3.7/site-packages/pandas/core/apply.py", line 296, in apply_standard
    values, self.f, axis=self.axis, dummy=dummy, labels=labels
  File "pandas/_libs/reduction.pyx", line 620, in pandas._libs.reduction.compute_reduction
  File "pandas/_libs/reduction.pyx", line 128, in pandas._libs.reduction.Reducer.get_result
  File "/home/geogateway/ModelofModels/data/GFMS_duration_fix.py", line 40, in <lambda>
    df['GFMS_Duration'] = df.apply(lambda row: 3 + int(row.GFMS_Duration0) if (row.GFMS_TotalArea_km > 100.0) else '0', axis = 1)
ValueError: cannot convert float NaN to integer
```

**Comment by webgisdeveloper** [comment]
The above will introduce another error later:
```
Traceback (most recent call last):
  File "datatool.py", line 632, in <module>
    main()
  File "datatool.py", line 627, in main
    run_cron_fix(args.fixdate)
  File "datatool.py", line 574, in run_cron_fix
    fix_duration(fix_list,folder=gfmsdata,fixfolder=gfmsdata_fix)
  File "/home/geogateway/ModelofModels/data/GFMS_duration_fix.py", line 31, in fix_duration
    df0 = pd.read_csv(csv_file)
  File "/home/geogateway/miniconda3/lib/python3.7/site-packages/pandas/io/parsers.py", line 676, in parser_f
    return _read(filepath_or_buffer, kwds)
  File "/home/geogateway/miniconda3/lib/python3.7/site-packages/pandas/io/parsers.py", line 448, in _read
    parser = TextFileReader(fp_or_buf, **kwds)
  File "/home/geogateway/miniconda3/lib/python3.7/site-packages/pandas/io/parsers.py", line 880, in __init__
    self._make_engine(self.engine)
  File "/home/geogateway/miniconda3/lib/python3.7/site-packages/pandas/io/parsers.py", line 1114, in _make_engine
    self._engine = CParserWrapper(self.f, **self.options)
  File "/home/geogateway/miniconda3/lib/python3.7/site-packages/pandas/io/parsers.py", line 1891, in __init__
    self._reader = parsers.TextReader(src, **kwds)
  File "pandas/_libs/parsers.pyx", line 374, in pandas._libs.parsers.TextReader.__cinit__
  File "pandas/_libs/parsers.pyx", line 674, in pandas._libs.parsers.TextReader._setup_parser_source
FileNotFoundError: [Errno 2] File cron_data/gfms/Flood_byStor_2020123021.csv does not exist: 'cron_data/gfms/Flood_byStor_2020123021.csv'
```

**Comment by webgisdeveloper** [comment]
delete the unsuccessful csv file in rawdata/gfms folder, then run fix-date again
